db:
  source: "jdbc"
  connection:
    url: "jdbc:postgresql://localhost:5432/books"
    username: "postgres"
    password: "labcom,2015"
  statements:
    ping: "DO 0"
    select-all-books: "SELECT * from Book"