db:
  source: "jdbc"
  connection:
    url: "jdbc:postgresql://localhost:5432/book"
    username: "postgres"
    password: "postgres"
  statements:
    ping: "DO 0"
    select-all-books: "SELECT * from book"